In [23]:
import pandas as pd
from dijkstar import Graph, find_path
import json
import numpy as np



# graph.add_edge(1,2,22)
# graph.add_edge(2,3,11)
# graph.dump(r'C:\Users\Omer\Documents\Python\stock scanner')

def load_users():
    with open(r'.\Users.json') as f:
        data = json.load(f)
    return data

def get_id_of_genre():
    dict = {}
    for row in range(0,1937):
        dict[df.iloc[row,0]] = row
    return dict
        
def create_graph():
    for row in range(0,1937):
        for col in range(1,1937):
            weight=int(df.iloc[row,col])
            if(weight == 0):
                continue
            else:
                graph.add_edge(row,col,1/weight)
        if(row%100==0):print(row)

# def build_matrinx():
    

def find_match(username,list_of_users,genres_id):
    matrix = []
    users = dict(list_of_users['Users'])
    target_user_genres = users[username]
    for name,genre in users.items():
        if(name != username):       #skip the target username
            matrix = []
            for target_genres in range(0,len(target_user_genres)):
                row= []
                for user_genres in range(0,len(genre)):
                    target = genres_id[target_user_genres[target_genres]]
                    user = genres_id[genre[user_genres]]
                    row.append(find_path(graph,target,user)[3])
                    # print('-----------------------------------------------------')
                    # print(username,' To ',name,'Genre: ',target_user_genres[target_genres],'-->',genre[user_genres])
                    # print(find_path(graph,target,user)[3])
                matrix.append(row)
        print('-----------------------------------------------------')
        print(username,' To ',name)        
        print(np.matrix(matrix))

def count_duplicates(list_of_users):
    list_of_counts = [] 
    users = dict(list_of_users['Users'])
    for user,geners in users.items():
        dict_of_counts = {item:geners.count(item) for item in geners}
        list_of_counts.append(dict_of_counts)
    print(list_of_counts)










In [26]:
count_duplicates(load_users())

[{'israeli pop': 1, 'rock': 3, 'pop': 4}, {'pop': 1, 'afropop': 1, 'israeli pop': 1}, {'latin metal': 1, 'rock': 1, 'alternative pop': 1}, {'pop': 1, 'classic rock': 1, 'israeli pop': 1}, {'pop': 1, 'rock': 1, 'israeli pop': 1}, {'latin funk': 1, 'classic rock': 1, 'israeli pop': 1}, {'pop': 1, 'rock': 1, 'israeli pop': 1}, {'latin tech house': 1, 'rock': 1, 'art pop': 1}, {'latin funk': 1, 'rock': 1, 'israeli pop': 1}, {'pop': 1, 'christian rock': 1, 'austrian pop': 1}]


In [27]:
df = pd.read_csv (r'.\network_matrix_final.csv')
graph = Graph()

In [29]:
create_graph()


0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700


In [21]:
find_match("User1",load_users(),get_id_of_genre())

-----------------------------------------------------
User1  To  User1
[]
-----------------------------------------------------
User1  To  User2
[[2.84444444 2.61393484 0.        ]
 [1.50696908 1.21596639 4.10795455]
 [1.50696908 1.21596639 4.10795455]
 [0.         1.1235363  4.17026379]
 [0.         1.1235363  4.17026379]
 [1.50696908 1.21596639 4.10795455]
 [0.         1.1235363  4.17026379]
 [0.         1.1235363  4.17026379]]
-----------------------------------------------------
User1  To  User3
[[1.5379902  2.39583333 1.4672619 ]
 [0.09848485 0.         0.01470588]
 [0.09848485 0.         0.01470588]
 [0.13461538 1.0625     0.04738016]
 [0.13461538 1.0625     0.04738016]
 [0.09848485 0.         0.01470588]
 [0.13461538 1.0625     0.04738016]
 [0.13461538 1.0625     0.04738016]]
-----------------------------------------------------
User1  To  User4
[[2.84444444 2.53854595 0.        ]
 [1.50696908 1.13943662 4.10795455]
 [1.50696908 1.13943662 4.10795455]
 [0.         1.12750455 4.1